### ISSUE TITLE
Do you even Rmd, bruh?

### ISSUE THREAD

**Issue by marcdotson** [andrewheiss/why-donors-donate#13]
Open issue for running problems with my learning how to write a paper using R Markdown. Feel free to pile on general correction, complaints, and resources here, @andrewheiss.

**Comment by marcdotson** [comment]
Hi, @andrewheiss. First legit question: What's the best way to parameterize data (e.g., posterior draws) for use in the paper? As far as I gather, we do this in the YAML, but I've seen it for values not data. Also...

![image](https://user-images.githubusercontent.com/29615257/64645215-98ff3b00-d3d1-11e9-84a8-a408d31932d6.png)

**Comment by marcdotson** [comment]
I realize this is probably a stupid question. Plus I found an RLadies presentation to go through, so...

**Comment by andrewheiss** [comment]
Like, how do you specify a specific RDS or CSV file to load?

**Comment by andrewheiss** [comment]
brb whipping up a reprex…

**Comment by andrewheiss** [comment]
Like so?

````
---
title: "Example"
output: html_document
params:
  dataset_to_use: "iris.rds"
  dataset_name: "magical flowers"
---

```{r save-rds, eval=FALSE, include=FALSE}
# This chunk doesn't get knit or anything—it just saves some built-in datasets
# as RDS files as an example. Run this first before knitting.
saveRDS(iris, "iris.rds")
saveRDS(mtcars, "mtcars.rds")
```

# Load data

First we load the `r params$dataset_name` dataset:

```{r}
df <- readRDS(params$dataset_to_use)
```

etc.
````

**Comment by andrewheiss** [comment]
Then later change the yaml to:

```
---
title: "Example"
output: html_document
params:
  dataset_to_use: "mtcars.rds"
  dataset_name: "overused cars"
---
```

and re-knit to use the other data

**Comment by marcdotson** [comment]
Awesome! Maybe it wasn't such a stupid question. Thanks.

**Comment by marcdotson** [comment]
I'm assuming this will be revealed when the working draft is posted, @andrewheiss, but I'm anxious to see how citations are handled as park of the R Markdown.

**Comment by andrewheiss** [comment]
K, I finally committed and pushed everything to master! You can see how citations are handled in the draft at <https://github.com/andrewheiss/why-donors-donate/blob/master/manuscript/manuscript.Rmd>. They're standard pandoc citations: see [here](https://evalsp20.classes.andrewheiss.com/reference/markdown/#citations) or [here](https://rmarkdown.rstudio.com/authoring_bibliographies_and_citations.html) for more details about their syntax.

The super good news is that you and Suparna should be able to compile the manuscript now too, as long as you install a few things. Check the comments at the top of `manuscript/Makefile` for details, or look at this repository here: <https://github.com/andrewheiss/portable-pandoc-magic>. Once you install everything, you should be able to run `make html` or `make tex` or whatever from the terminal and generate the manuscript.

Any edits should be done in `manuscript.Rmd`, *not* `manuscript.md`, since the vanilla markdown file is generated from the Rmd (and then turned into HTML/Word/TeX/whatever). I've disabled knitting for that file—if you try to knit `manuscript.Rmd` from RStudio, you'll get an error. You have to use `make WHATEVER` from the terminal.

**Comment by marcdotson** [comment]
This has morphed into direct conversations, so I'm going to go ahead and close this comment to feel like I'm doing something.
