### ISSUE TITLE
Prepare for data analysis

### ISSUE THREAD

**Issue by marcdotson** [andrewheiss/why-donors-donate#3]
@meghop, @sabrinaweiler, @MitchellKimball, @maryrosemcqueen we can prepare for analyzing the data by simulating survey and conjoint data and setting up for the analysis. Time to code! We can talk about this in our meeting next week or, if you have time, stop by my office tomorrow.

**Comment by marcdotson** [comment]
With the hypothesis section of the pre-registration taking shape, we have a better idea of what to prepare for. The data analysis prep will include:

- Testing the hierarchical multinomial logit model, including the use of various covariates.
- Plotting aggregate marginal posteriors and comparing 95% confidence intervals, including the use of various covariates.
- Preparing for counterfactual analysis using a market simulator.

**Comment by marcdotson** [comment]
@andrewheiss two organization-related questions:

- Do we include Stan files in the `/R` directory?
- Should we include model calibration within an Rmd file in `/analysis`? I'd assumed we'd just be working with model output in the Rmd files that are posted online since it'll take a while for these models to run.

**Comment by andrewheiss** [comment]
If we want Stan files to be precompiled as functions like rstanarm's stuff, they have to go in a bunch of weird places, and [**rstantools**](https://github.com/stan-dev/rstantools) takes care of that (like, some parts go in `/inst/include/`, some in `/tools/`, and some in `/src/`). 

The actual Stan files typically go in `/src/stan_files/` (like [here](https://github.com/andrewheiss/ngo-crackdowns-philanthropy/tree/master/src/stan_files)).

Even if we don't precompile all the files, we can still keep them in `/src/stan_files` and then reference them in Rmd files with `here("src", "stan_files", "blah.stan")`

---

Things that take forever to run shouldn't go in `/analysis` as R Markdown files, since those files all get re-knit constantly. Instead, we can put them in regular R scripts either in `/analysis/` or somewhere like `/analysis/calibration/` or whatever, and then save their output as .rds files to `/data/derived_data`

**Comment by marcdotson** [comment]
I'll leave precompiling, if you want it, to you. :)

Good to know -- I'll put the model calibration scripts (both R and Stan) in an `/analysis` subfolder.

**Comment by marcdotson** [comment]
Created `/src/stan_files` (not an `/analysis` subfolder) and finished set-up for analysis, including data cleaning. See PR #10.
